-- =================================================================================
-- BlueKhata — Complete Production Database Installer
-- Generated by reverse-engineering the Flutter project (lib/**) against the
-- existing supabase/migrations/0001–0004 SQL, so this file is the single
-- source of truth going forward.
--
-- SAFE TO RE-RUN: every statement is idempotent (create/drop-if-exists),
-- so pasting this into the Supabase SQL Editor and pressing RUN multiple
-- times will not error or duplicate objects.
--
-- WHAT CHANGED VS THE ORIGINAL 4 MIGRATIONS
--   1. public.users -> public.profiles (RENAMED)
--      Flutter's AuthRepository (lib/features/authentication/data/
--      repositories/auth_repository.dart) reads/writes a table literally
--      named `profiles` with columns `id`, `full_name`, `phone`. The
--      original migrations only created `public.users` (columns
--      `display_name`, no `full_name`) — every call from the app would
--      have failed with "relation public.profiles does not exist" or,
--      after a naive add-a-table fix, left two disconnected user tables.
--      Fix: the profile table is now named `profiles`, its name column is
--      `full_name` (matching the Flutter upsert payload exactly), and
--      every foreign key that used to point at `public.users(id)` now
--      points at `public.profiles(id)`. This is the ONLY breaking
--      mismatch found between the app and the database — see
--      flutter_database_compatibility_report.md for the full audit.
--   2. Everything else (businesses, business_members, customers,
--      ledger_entries, cashbook_entries, bank_accounts, bank_transactions,
--      categories, products, inventory_logs, invoices, invoice_items,
--      staff, attendance, salary, reminders, notifications, announcements,
--      banners, settings, audit_logs, deleted_records, backup_history)
--      already matched the Flutter code exactly and is carried over
--      unchanged in structure, just renumbered into one file.
--   3. Additive, non-breaking extras requested by the install spec that
--      the Flutter code does not yet call, but which the schema needs to
--      be "complete": a `payment_methods` lookup table + seed data,
--      storage buckets/policies for every *_url column, and two
--      dashboard views. These are clearly marked "ADDITIVE" below and
--      cannot break any existing query because nothing in lib/ references
--      them yet.
-- =================================================================================

-- =================================================================================
-- SECTION 0 — EXTENSIONS
-- =================================================================================
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

-- =================================================================================
-- SECTION 1 — SHARED FUNCTIONS (defined early; referenced by triggers below)
-- =================================================================================

-- Generic updated_at maintenance, reused by every table that has the column.
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- =================================================================================
-- SECTION 2 — PROFILES  (renamed from `users` to match Flutter's `profiles` calls)
-- =================================================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_url text,
  preferred_language text default 'en',
  role text not null default 'business_owner'
    check (role in ('super_admin','business_owner','manager','cashier','staff','viewer')),
  is_blocked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_profiles_touch on public.profiles;
create trigger trg_profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- ADDITIVE (safety net, does not conflict with Flutter's own upsert-on-signup):
-- auto-create a bare profile row whenever a new auth.users row appears, so a
-- profile always exists even for users created outside signUp() (magic link,
-- OAuth, admin invite, etc). Flutter's ensureProfile()/upsert still works
-- unchanged — it will simply update the row this trigger already created.
create or replace function public.handle_new_auth_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), null)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_auth_user_created on auth.users;
create trigger trg_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

alter table public.profiles enable row level security;

drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self on public.profiles
  for select using (id = auth.uid());
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
  for update using (id = auth.uid());
drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles
  for insert with check (id = auth.uid());

-- =================================================================================
-- SECTION 3 — BUSINESSES
-- =================================================================================
create table if not exists public.businesses (
  id uuid primary key default uuid_generate_v4(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  logo_url text,
  banner_url text,
  business_type text default 'General',
  currency text not null default 'PKR',
  address text,
  tax_number text,
  phone text,
  email text,
  is_archived boolean not null default false,
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_businesses_owner on public.businesses(owner_id);

drop trigger if exists trg_businesses_touch on public.businesses;
create trigger trg_businesses_touch before update on public.businesses
  for each row execute function public.touch_updated_at();

alter table public.businesses enable row level security;

-- =================================================================================
-- SECTION 4 — BUSINESS_MEMBERS (role-based access per business)
-- =================================================================================
create table if not exists public.business_members (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'staff'
    check (role in ('owner','manager','cashier','staff','viewer')),
  status text not null default 'active' check (status in ('active','invited','removed')),
  created_at timestamptz not null default now(),
  unique(business_id, user_id)
);

create index if not exists idx_business_members_business on public.business_members(business_id);
create index if not exists idx_business_members_user on public.business_members(user_id);

alter table public.business_members enable row level security;

-- helper: is the current user a member (any role) of a business?
-- Defined after businesses/business_members exist, before it's used in policies.
create or replace function public.is_business_member(target_business_id uuid)
returns boolean language sql stable as $$
  select exists (
    select 1 from public.businesses b
    where b.id = target_business_id and b.owner_id = auth.uid()
  ) or exists (
    select 1 from public.business_members m
    where m.business_id = target_business_id
      and m.user_id = auth.uid()
      and m.status = 'active'
  );
$$;

-- businesses policies (declared here, after is_business_member exists)
drop policy if exists businesses_select on public.businesses;
create policy businesses_select on public.businesses
  for select using (public.is_business_member(id));
drop policy if exists businesses_insert on public.businesses;
create policy businesses_insert on public.businesses
  for insert with check (owner_id = auth.uid());
drop policy if exists businesses_update on public.businesses;
create policy businesses_update on public.businesses
  for update using (owner_id = auth.uid());
drop policy if exists businesses_delete on public.businesses;
create policy businesses_delete on public.businesses
  for delete using (owner_id = auth.uid());

drop policy if exists business_members_select on public.business_members;
create policy business_members_select on public.business_members
  for select using (public.is_business_member(business_id));
drop policy if exists business_members_write on public.business_members;
create policy business_members_write on public.business_members
  for all using (
    exists (select 1 from public.businesses b where b.id = business_id and b.owner_id = auth.uid())
  );

-- =================================================================================
-- SECTION 5 — CUSTOMERS (also used for suppliers/vendors via is_supplier)
-- =================================================================================
create table if not exists public.customers (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  phone text,
  address text,
  cnic text,
  image_url text,
  opening_balance numeric(14,2) not null default 0,
  current_balance numeric(14,2) not null default 0,
  credit_limit numeric(14,2),
  notes text,
  tags text[] not null default '{}',
  is_favorite boolean not null default false,
  is_supplier boolean not null default false,
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_customers_business on public.customers(business_id);
create index if not exists idx_customers_name on public.customers using gin (name gin_trgm_ops);

-- Initialize current_balance from opening_balance on insert.
create or replace function public.set_customer_initial_balance()
returns trigger language plpgsql as $$
begin
  new.current_balance := coalesce(new.opening_balance, 0);
  return new;
end;
$$;

drop trigger if exists trg_customers_initial_balance on public.customers;
create trigger trg_customers_initial_balance
  before insert on public.customers
  for each row execute function public.set_customer_initial_balance();

drop trigger if exists trg_customers_touch on public.customers;
create trigger trg_customers_touch before update on public.customers
  for each row execute function public.touch_updated_at();

alter table public.customers enable row level security;

drop policy if exists customers_select on public.customers;
create policy customers_select on public.customers
  for select using (public.is_business_member(business_id));
drop policy if exists customers_insert on public.customers;
create policy customers_insert on public.customers
  for insert with check (public.is_business_member(business_id));
drop policy if exists customers_update on public.customers;
create policy customers_update on public.customers
  for update using (public.is_business_member(business_id));
drop policy if exists customers_delete on public.customers;
create policy customers_delete on public.customers
  for delete using (public.is_business_member(business_id));

-- =================================================================================
-- SECTION 6 — LEDGER_ENTRIES (core credit/debit customer ledger)
-- Matches lib/features/ledger/data/repositories/ledger_repository.dart exactly:
-- business_id, customer_id, type, amount, balance_after, note, category,
-- attachment_urls, entry_date, created_by, is_deleted, deleted_at, created_at.
-- =================================================================================
create table if not exists public.ledger_entries (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  type text not null check (type in ('credit','debit')),
  amount numeric(14,2) not null check (amount > 0),
  balance_after numeric(14,2) not null default 0,
  note text,
  category text,
  attachment_urls text[] not null default '{}',
  entry_date timestamptz not null default now(),
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_ledger_customer on public.ledger_entries(customer_id, entry_date desc);
create index if not exists idx_ledger_business on public.ledger_entries(business_id, entry_date desc);

drop trigger if exists trg_ledger_entries_touch on public.ledger_entries;
create trigger trg_ledger_entries_touch before update on public.ledger_entries
  for each row execute function public.touch_updated_at();

-- Applies a new entry's effect on the customer's running balance.
-- credit ("you gave") increases balance owed to you; debit ("you received") decreases it.
create or replace function public.apply_ledger_entry_balance()
returns trigger language plpgsql as $$
declare
  delta numeric(14,2);
  new_balance numeric(14,2);
begin
  delta := case when new.type = 'credit' then new.amount else -new.amount end;

  update public.customers
     set current_balance = current_balance + delta
   where id = new.customer_id
   returning current_balance into new_balance;

  new.balance_after := new_balance;
  return new;
end;
$$;

drop trigger if exists trg_ledger_entries_apply_balance on public.ledger_entries;
create trigger trg_ledger_entries_apply_balance
  before insert on public.ledger_entries
  for each row execute function public.apply_ledger_entry_balance();

-- Reverses a soft-deleted entry's effect on the running balance.
-- Fires on UPDATE because Flutter's softDeleteEntry() does an UPDATE
-- (is_deleted: true), never a hard DELETE.
create or replace function public.reverse_ledger_entry_balance()
returns trigger language plpgsql as $$
declare
  delta numeric(14,2);
begin
  if new.is_deleted = true and old.is_deleted = false then
    delta := case when old.type = 'credit' then -old.amount else old.amount end;
    update public.customers
       set current_balance = current_balance + delta
     where id = old.customer_id;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_ledger_entries_reverse_on_delete on public.ledger_entries;
create trigger trg_ledger_entries_reverse_on_delete
  before update on public.ledger_entries
  for each row execute function public.reverse_ledger_entry_balance();

alter table public.ledger_entries enable row level security;

drop policy if exists ledger_entries_select on public.ledger_entries;
create policy ledger_entries_select on public.ledger_entries
  for select using (public.is_business_member(business_id));
drop policy if exists ledger_entries_insert on public.ledger_entries;
create policy ledger_entries_insert on public.ledger_entries
  for insert with check (public.is_business_member(business_id) and created_by = auth.uid());
drop policy if exists ledger_entries_update on public.ledger_entries;
create policy ledger_entries_update on public.ledger_entries
  for update using (public.is_business_member(business_id));

-- =================================================================================
-- SECTION 7 — CASHBOOK_ENTRIES (cash in / cash out / income / expense / transfer)
-- Schema-ready module; no Flutter repository wired yet (see README "Not yet built").
-- =================================================================================
create table if not exists public.cashbook_entries (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  type text not null check (type in ('cash_in','cash_out','income','expense','transfer')),
  amount numeric(14,2) not null check (amount > 0),
  category text,
  note text,
  entry_date timestamptz not null default now(),
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_cashbook_business on public.cashbook_entries(business_id, entry_date desc);

alter table public.cashbook_entries enable row level security;
drop policy if exists cashbook_select on public.cashbook_entries;
create policy cashbook_select on public.cashbook_entries
  for select using (public.is_business_member(business_id));
drop policy if exists cashbook_insert on public.cashbook_entries;
create policy cashbook_insert on public.cashbook_entries
  for insert with check (public.is_business_member(business_id) and created_by = auth.uid());

-- =================================================================================
-- SECTION 8 — BANK_ACCOUNTS + BANK_TRANSACTIONS
-- Schema-ready module; no Flutter repository wired yet.
-- =================================================================================
create table if not exists public.bank_accounts (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  bank_name text not null,
  account_title text not null,
  account_number text,
  current_balance numeric(14,2) not null default 0,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.bank_transactions (
  id uuid primary key default uuid_generate_v4(),
  bank_account_id uuid not null references public.bank_accounts(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  type text not null check (type in ('deposit','withdrawal','transfer','cheque')),
  amount numeric(14,2) not null check (amount > 0),
  note text,
  cheque_number text,
  cheque_status text check (cheque_status in ('pending','cleared','bounced')),
  entry_date timestamptz not null default now(),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_bank_txn_account on public.bank_transactions(bank_account_id, entry_date desc);

alter table public.bank_accounts enable row level security;
alter table public.bank_transactions enable row level security;

drop policy if exists bank_accounts_select on public.bank_accounts;
create policy bank_accounts_select on public.bank_accounts
  for select using (public.is_business_member(business_id));
drop policy if exists bank_accounts_write on public.bank_accounts;
create policy bank_accounts_write on public.bank_accounts
  for all using (public.is_business_member(business_id));

drop policy if exists bank_txn_select on public.bank_transactions;
create policy bank_txn_select on public.bank_transactions
  for select using (public.is_business_member(business_id));
drop policy if exists bank_txn_insert on public.bank_transactions;
create policy bank_txn_insert on public.bank_transactions
  for insert with check (public.is_business_member(business_id) and created_by = auth.uid());

-- =================================================================================
-- SECTION 9 — CATEGORIES, PRODUCTS, INVENTORY_LOGS
-- Schema-ready module; no Flutter repository wired yet.
-- =================================================================================
create table if not exists public.categories (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  category_id uuid references public.categories(id),
  name text not null,
  sku text,
  barcode text,
  unit text not null default 'pcs',
  purchase_price numeric(14,2) not null default 0,
  selling_price numeric(14,2) not null default 0,
  stock_quantity numeric(14,2) not null default 0,
  low_stock_threshold numeric(14,2) not null default 5,
  supplier_id uuid references public.customers(id),
  image_url text,
  is_deleted boolean not null default false,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_business on public.products(business_id);
create index if not exists idx_products_barcode on public.products(barcode);

drop trigger if exists trg_products_touch on public.products;
create trigger trg_products_touch before update on public.products
  for each row execute function public.touch_updated_at();

create table if not exists public.inventory_logs (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  change_type text not null check (change_type in ('purchase','sale','adjustment','return')),
  quantity_delta numeric(14,2) not null,
  note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

-- Keeps products.stock_quantity in sync with inventory_logs.
create or replace function public.apply_inventory_log()
returns trigger language plpgsql as $$
begin
  update public.products
     set stock_quantity = stock_quantity + new.quantity_delta
   where id = new.product_id;
  return new;
end;
$$;

drop trigger if exists trg_inventory_logs_apply on public.inventory_logs;
create trigger trg_inventory_logs_apply
  after insert on public.inventory_logs
  for each row execute function public.apply_inventory_log();

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.inventory_logs enable row level security;

drop policy if exists categories_all on public.categories;
create policy categories_all on public.categories for all using (public.is_business_member(business_id));
drop policy if exists products_all on public.products;
create policy products_all on public.products for all using (public.is_business_member(business_id));
drop policy if exists inventory_logs_all on public.inventory_logs;
create policy inventory_logs_all on public.inventory_logs for all using (public.is_business_member(business_id));

-- =================================================================================
-- SECTION 10 — INVOICES + INVOICE_ITEMS
-- Schema-ready module; no Flutter repository wired yet.
-- =================================================================================
create table if not exists public.invoices (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  customer_id uuid references public.customers(id),
  invoice_type text not null default 'invoice'
    check (invoice_type in ('invoice','quotation','receipt','purchase_bill')),
  invoice_number text not null,
  status text not null default 'pending' check (status in ('paid','pending','partial','cancelled')),
  subtotal numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  tax numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  amount_paid numeric(14,2) not null default 0,
  notes text,
  is_deleted boolean not null default false,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id, invoice_number)
);

drop trigger if exists trg_invoices_touch on public.invoices;
create trigger trg_invoices_touch before update on public.invoices
  for each row execute function public.touch_updated_at();

create table if not exists public.invoice_items (
  id uuid primary key default uuid_generate_v4(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  product_id uuid references public.products(id),
  description text not null,
  quantity numeric(14,2) not null default 1,
  unit_price numeric(14,2) not null default 0,
  line_total numeric(14,2) not null default 0
);

alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;

drop policy if exists invoices_all on public.invoices;
create policy invoices_all on public.invoices for all using (public.is_business_member(business_id));
drop policy if exists invoice_items_all on public.invoice_items;
create policy invoice_items_all on public.invoice_items for all using (
  exists (select 1 from public.invoices i where i.id = invoice_id and public.is_business_member(i.business_id))
);

-- =================================================================================
-- SECTION 11 — STAFF, ATTENDANCE, SALARY
-- Schema-ready module; no Flutter repository wired yet.
-- =================================================================================
create table if not exists public.staff (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid references public.profiles(id),
  full_name text not null,
  phone text,
  role_title text,
  monthly_salary numeric(14,2) default 0,
  joined_at date default current_date,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id uuid primary key default uuid_generate_v4(),
  staff_id uuid not null references public.staff(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  date date not null,
  status text not null check (status in ('present','absent','leave','half_day')),
  check_in time,
  check_out time,
  created_at timestamptz not null default now(),
  unique(staff_id, date)
);

create table if not exists public.salary (
  id uuid primary key default uuid_generate_v4(),
  staff_id uuid not null references public.staff(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  month date not null,
  base_amount numeric(14,2) not null default 0,
  bonus numeric(14,2) not null default 0,
  advance numeric(14,2) not null default 0,
  overtime numeric(14,2) not null default 0,
  net_paid numeric(14,2) not null default 0,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.staff enable row level security;
alter table public.attendance enable row level security;
alter table public.salary enable row level security;

drop policy if exists staff_all on public.staff;
create policy staff_all on public.staff for all using (public.is_business_member(business_id));
drop policy if exists attendance_all on public.attendance;
create policy attendance_all on public.attendance for all using (public.is_business_member(business_id));
drop policy if exists salary_all on public.salary;
create policy salary_all on public.salary for all using (public.is_business_member(business_id));

-- =================================================================================
-- SECTION 12 — REMINDERS
-- Schema-ready module; no Flutter repository wired yet.
-- =================================================================================
create table if not exists public.reminders (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  remind_at timestamptz not null,
  channel text not null default 'push' check (channel in ('push','sms','whatsapp')),
  recurring boolean not null default false,
  recurrence_interval_days integer,
  status text not null default 'pending' check (status in ('pending','sent','dismissed')),
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_reminders_due on public.reminders(remind_at) where status = 'pending';

alter table public.reminders enable row level security;
drop policy if exists reminders_all on public.reminders;
create policy reminders_all on public.reminders for all using (public.is_business_member(business_id));

-- =================================================================================
-- SECTION 13 — NOTIFICATIONS (per-user inbox, fed by FCM sends)
-- Schema-ready module; no Flutter repository wired yet.
-- =================================================================================
create table if not exists public.notifications (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade,
  business_id uuid references public.businesses(id),
  type text not null check (type in (
    'announcement','business_update','payment_reminder','due_reminder',
    'inventory_alert','low_stock','invoice_created','invoice_paid',
    'promotional_campaign','system_update','emergency_alert'
  )),
  title text not null,
  body text,
  data jsonb default '{}',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user on public.notifications(user_id, created_at desc);

alter table public.notifications enable row level security;
drop policy if exists notifications_select on public.notifications;
create policy notifications_select on public.notifications for select using (user_id = auth.uid());

-- =================================================================================
-- SECTION 14 — ADMIN-MANAGED CONTENT (announcements, banners, settings)
-- =================================================================================
create table if not exists public.announcements (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  body text not null,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.banners (
  id uuid primary key default uuid_generate_v4(),
  image_url text not null,
  link_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create or replace function public.is_super_admin()
returns boolean language sql stable as $$
  select exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'super_admin');
$$;

alter table public.announcements enable row level security;
alter table public.banners enable row level security;
alter table public.settings enable row level security;

drop policy if exists announcements_select on public.announcements;
create policy announcements_select on public.announcements for select using (is_active = true);
drop policy if exists announcements_admin_write on public.announcements;
create policy announcements_admin_write on public.announcements for all using (public.is_super_admin());

drop policy if exists banners_select on public.banners;
create policy banners_select on public.banners for select using (is_active = true);
drop policy if exists banners_admin_write on public.banners;
create policy banners_admin_write on public.banners for all using (public.is_super_admin());

drop policy if exists settings_select on public.settings;
create policy settings_select on public.settings for select using (true);
drop policy if exists settings_admin_write on public.settings;
create policy settings_admin_write on public.settings for all using (public.is_super_admin());

-- =================================================================================
-- SECTION 15 — AUDIT_LOGS, DELETED_RECORDS, BACKUP_HISTORY
-- =================================================================================
create table if not exists public.audit_logs (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid references public.businesses(id),
  user_id uuid references public.profiles(id),
  action text not null,
  table_name text,
  record_id uuid,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.deleted_records (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid references public.businesses(id),
  table_name text not null,
  record_id uuid not null,
  record_snapshot jsonb not null,
  deleted_by uuid references public.profiles(id),
  deleted_at timestamptz not null default now()
);

create table if not exists public.backup_history (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid references public.businesses(id),
  initiated_by uuid references public.profiles(id),
  backup_url text,
  status text not null default 'completed' check (status in ('pending','completed','failed')),
  created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;
alter table public.deleted_records enable row level security;
alter table public.backup_history enable row level security;

drop policy if exists audit_logs_select on public.audit_logs;
create policy audit_logs_select on public.audit_logs for select using (public.is_business_member(business_id));
drop policy if exists deleted_records_select on public.deleted_records;
create policy deleted_records_select on public.deleted_records for select using (public.is_business_member(business_id));
drop policy if exists backup_history_select on public.backup_history;
create policy backup_history_select on public.backup_history for select using (public.is_business_member(business_id));

-- =================================================================================
-- SECTION 16 — ADDITIVE: PAYMENT_METHODS LOOKUP TABLE
-- Not called by any current Flutter code (no repository references it yet),
-- but included because it's a standard companion to cashbook/bank/invoice
-- modules and was explicitly requested in the install spec ("Default Payment
-- Methods"). Safe to ignore until a payments feature is built — it cannot
-- break any existing query.
-- =================================================================================
create table if not exists public.payment_methods (
  id uuid primary key default uuid_generate_v4(),
  business_id uuid references public.businesses(id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(business_id, name)
);

alter table public.payment_methods enable row level security;
drop policy if exists payment_methods_select on public.payment_methods;
create policy payment_methods_select on public.payment_methods
  for select using (business_id is null or public.is_business_member(business_id));
drop policy if exists payment_methods_write on public.payment_methods;
create policy payment_methods_write on public.payment_methods
  for all using (business_id is not null and public.is_business_member(business_id));

-- =================================================================================
-- SECTION 17 — ADDITIVE: DASHBOARD VIEWS
-- Read-only convenience views for the reports/analytics module mentioned in
-- README's "Not yet built" list. Inherit RLS from their base tables
-- automatically (views run with the querying user's permissions here since
-- they are not security definer).
-- =================================================================================
create or replace view public.business_dashboard_summary as
select
  b.id as business_id,
  b.name as business_name,
  b.currency,
  count(distinct c.id) filter (where c.is_deleted = false) as total_customers,
  coalesce(sum(c.current_balance) filter (where c.is_deleted = false and c.current_balance > 0), 0) as total_receivable,
  coalesce(sum(abs(c.current_balance)) filter (where c.is_deleted = false and c.current_balance < 0), 0) as total_payable
from public.businesses b
left join public.customers c on c.business_id = b.id
where b.is_deleted = false
group by b.id, b.name, b.currency;

create or replace view public.daily_ledger_summary as
select
  le.business_id,
  date_trunc('day', le.entry_date) as entry_day,
  sum(le.amount) filter (where le.type = 'credit') as total_credit,
  sum(le.amount) filter (where le.type = 'debit') as total_debit
from public.ledger_entries le
where le.is_deleted = false
group by le.business_id, date_trunc('day', le.entry_date);

-- =================================================================================
-- SECTION 18 — ADDITIVE: STORAGE BUCKETS + STORAGE POLICIES
-- Inferred from every *_url column in the schema (logo_url, banner_url,
-- image_url, avatar_url, attachment_urls). No .storage/.bucket() call exists
-- in lib/ yet (Flutter currently just stores whatever URL string it is
-- given), so these buckets are provisioned ahead of that integration and are
-- safe no-ops until the app starts uploading files.
-- =================================================================================
insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('business-assets', 'business-assets', true),
  ('customer-images', 'customer-images', true),
  ('ledger-attachments', 'ledger-attachments', false),
  ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Avatars: user manages their own folder (avatars/<uid>/...).
drop policy if exists avatars_read on storage.objects;
create policy avatars_read on storage.objects
  for select using (bucket_id = 'avatars');
drop policy if exists avatars_write on storage.objects;
create policy avatars_write on storage.objects
  for insert with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists avatars_update on storage.objects;
create policy avatars_update on storage.objects
  for update using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists avatars_delete on storage.objects;
create policy avatars_delete on storage.objects
  for delete using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Business-scoped buckets: folder convention <bucket>/<business_id>/..., gated
-- by is_business_member() so only members of that business can read/write.
drop policy if exists business_assets_read on storage.objects;
create policy business_assets_read on storage.objects
  for select using (bucket_id = 'business-assets');
drop policy if exists business_assets_write on storage.objects;
create policy business_assets_write on storage.objects
  for all using (
    bucket_id = 'business-assets'
    and public.is_business_member(((storage.foldername(name))[1])::uuid)
  );

drop policy if exists customer_images_read on storage.objects;
create policy customer_images_read on storage.objects
  for select using (bucket_id = 'customer-images');
drop policy if exists customer_images_write on storage.objects;
create policy customer_images_write on storage.objects
  for all using (
    bucket_id = 'customer-images'
    and public.is_business_member(((storage.foldername(name))[1])::uuid)
  );

drop policy if exists ledger_attachments_rw on storage.objects;
create policy ledger_attachments_rw on storage.objects
  for all using (
    bucket_id = 'ledger-attachments'
    and public.is_business_member(((storage.foldername(name))[1])::uuid)
  );

drop policy if exists product_images_read on storage.objects;
create policy product_images_read on storage.objects
  for select using (bucket_id = 'product-images');
drop policy if exists product_images_write on storage.objects;
create policy product_images_write on storage.objects
  for all using (
    bucket_id = 'product-images'
    and public.is_business_member(((storage.foldername(name))[1])::uuid)
  );

-- =================================================================================
-- SECTION 19 — SEED DATA
-- =================================================================================

-- Global default payment methods (business_id null = available to everyone;
-- a business can add its own by inserting a row with its own business_id).
insert into public.payment_methods (business_id, name, is_default, is_active)
values
  (null, 'Cash', true, true),
  (null, 'Bank Transfer', false, true),
  (null, 'JazzCash', false, true),
  (null, 'EasyPaisa', false, true),
  (null, 'Cheque', false, true),
  (null, 'Credit Card', false, true)
on conflict (business_id, name) do nothing;

-- Global default settings row (site-wide config the admin panel can edit).
insert into public.settings (key, value)
values ('app_defaults', jsonb_build_object(
  'default_currency', 'PKR',
  'app_name', 'BlueKhata',
  'powered_by', 'Zenvyro Labs'
))
on conflict (key) do nothing;

-- Note: "Default Categories" are intentionally NOT seeded globally here.
-- public.categories.business_id is NOT NULL (every category belongs to one
-- business), so there is nothing to seed until a business exists. When a
-- new business is created, insert its starter categories client-side or add
-- a trigger on public.businesses if you want this automated — see
-- migration_report.md for the recommended snippet.

-- =================================================================================
-- END OF INSTALLER
-- =================================================================================
